- name: checking service status
  hosts: 172.16.16.28
  tasks:
  - name: checking service status
    command: systemctl status "{{ item }}"
    with_items:
    - mysql
    - xinetd
    register: result
    ignore_errors: yes
  - name: showing report
    debug:
     var: result
